baseURL = 'https://jackmortdt.github.io/nvim-presentation/'
languageCode = 'en-us'
title = 'Nvim presentation'
theme = ["github.com/dzello/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = false

[params.reveal_hugo]
highlight_theme = "github"
slide_number = true
width = 1024
height = 768